plugins {
    id 'com.android.application'
}

android {
    namespace 'com.shreyasss.meterinspection'
    compileSdk 36

    defaultConfig {
        applicationId 'com.shreyasss.meterinspection'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
        buildConfigField 'String', 'WEB_APP_URL', '"https://script.google.com/macros/s/AKfycbwSspkFY0_DPPjSeHy90ajh1Yw7qO2lfag62OznlDeB_hp9krJfWkzrRgf4H1J8ig77Dg/exec"'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.browser:browser:1.10.0'
}
